### PR TITLE
Update zombies.txt

### PR DESCRIPTION
**Pull request by mnot**
Doesn't work

### CODE REVIEW

**Comment by epsylon** [comment]
@mnot this list is provided as an example... it is your task to maintain it updated.

**Comment by mnot** [comment]
And yet many of your users are not, which causes a lot of spurious request to my Web site. Please remove it from your list.

**Comment by epsylon** [comment]
@mnot your request has been done -> https://github.com/epsylon/ufonet/blob/master/botnet/zombies.txt . Thanks!

**Comment by mnot** [comment]
Thank you!

**Pull request closed without merging**
