### PR TITLE
Update Python interpreter version in README.md

### PR DESCRIPTION
**Pull request by khaelou**
Prevents users from seeing 'Sorry' command log message on python version.

### CODE REVIEW

**Comment by khaelou** [comment]
> Prevents users from seeing 'Sorry' command log message on python version.

Should also be updated on website.

**Comment by epsylon** [comment]
This proposal will be taken in consideration for next update.

Thanks!

**Comment by epsylon** [comment]
@khaelou your request has been added on this update -> https://github.com/epsylon/ufonet/commit/d9980f21822570672bd4195f9790adef8ef2f1b6

**Comment by khaelou** [comment]
Great!

**Pull request closed without merging**
