### PR TITLE
Insert video readme

### PR DESCRIPTION
**Pull request by trollmad3**
Some people starting out with ufonet may have problems setting it up. This video can help them.

### CODE REVIEW

**Comment by epsylon** [comment]
Denied @trollmad3, sorry!

There are around ~7000 videos on Youtube about UFOnet, with different laguages, etc. I think that it is better to don't priorize any. Even I have created some and thay aren't on README. 

Ex: https://ufonet.03c8.net/ufonet/ufonet-hydra.ogv

**Comment by epsylon** [comment]
By the way. You have at "Board" (crypto-forum) a topic called: #Media, in which you can include your videos and share them with rest of masters.. Try better this other way, as others did.

**Comment by trollmad3** [comment]
So where do you think I can put this video?

**Comment by epsylon** [comment]
Even taking a pure definition, UFONet is also a DarkNet. So, you can add your videos on any "mothership" which provide you access. 
For example, you have by default one when using "--gui".
Try visiting: "Board" section. After that, try "Write", choose a Topic (#Media is a good one for your goal) and publish it... Other UFONet users will recieve it after connect to this "ship".

**Pull request closed without merging**
